export const ADD_RECORD = 'ADD_RECORD'
export const DELETE_RECORD = 'DELETE_RECORD'
export const ON_CHANGE_TRAINING_NAME = 'ON_CHANGE_TRAINING_NAME'
export const ON_CHANG_SET_COUNT = 'ON_CHANG_SET_COUNT'